### ISSUE TITLE
Crash on world load if config file does not exist

### ISSUE THREAD

**Issue by torzod** [Steveplays28/biome-fog#21] opened 2023-07-28 04:24 UTC
On loading the world, if the config file does not exist, the game crashes. 
here is the relevant part of the log:

```
[23:21:09] [Render thread/ERROR]: Exception thrown while invoking ClientPlayConnectionEvents.JOIN
java.lang.NullPointerException: Cannot read field "blackListedWorlds" because "io.github.steveplays28.biomefog.config.BiomeFogConfigLoader$BiomeFogConfigurations.BLACKLISTED_WORLDS" is null
	at io.github.steveplays28.biomefog.util.WorldUtil.isWorldBlacklisted(WorldUtil.java:40) ~[biome-fog-1.1.0+mc1.19.3_or_higher.jar:?]
	at io.github.steveplays28.biomefog.client.BiomeFogClient.lambda$onInitializeClient$2(BiomeFogClient.java:41) ~[biome-fog-1.1.0+mc1.19.3_or_higher.jar:?]
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$2(ClientPlayConnectionEvents.java:50) ~[fabric-networking-api-v1-1.3.9+b3afc78b77-866279913ec241f1.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.onServerReady(ClientPlayNetworkAddon.java:70) ~[fabric-networking-api-v1-1.3.9+b3afc78b77-866279913ec241f1.jar:?]
	at net.minecraft.class_634.handler$cna000$fabric-networking-api-v1$handleServerPlayReady(class_634.java:3763) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:465) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
	
	
	[23:21:11] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot read field "fogColor" because "io.github.steveplays28.biomefog.config.BiomeFogConfigLoader$BiomeFogConfigurations.CONFIG" is null
	at net.minecraft.class_758.handler$zcd000$biome-fog$renderInject(class_758.java:1166) ~[client-intermediary.jar:?]
	at net.minecraft.class_758.method_3210(class_758.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1232) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]

```

**Comment by Steveplays28** [comment] 2023-07-28 11:06
I've made a fix for this, will release soon. Duplicate of #17.

**Closed as not planned by Steveplays28** 2023-07-28 11:06 UTC
Labels: bug, duplicate, crash
